#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : geocode-glib
Version  : 3.26.4
Release  : 19
URL      : https://download.gnome.org/sources/geocode-glib/3.26/geocode-glib-3.26.4.tar.xz
Source0  : https://download.gnome.org/sources/geocode-glib/3.26/geocode-glib-3.26.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause LGPL-2.0
Requires: geocode-glib-data = %{version}-%{release}
Requires: geocode-glib-lib = %{version}-%{release}
Requires: geocode-glib-libexec = %{version}-%{release}
Requires: geocode-glib-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : libsoup-dev
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libsoup-2.4)

%description
geocode-glib is a convenience library for the geocoding (finding longitude,
and latitude from an address) and reverse geocoding (finding an address from
coordinates). It uses Nominatim service to achieve that. It also caches
(reverse-)geocoding requests for faster results and to avoid unnecessary server
load.

%package data
Summary: data components for the geocode-glib package.
Group: Data

%description data
data components for the geocode-glib package.


%package dev
Summary: dev components for the geocode-glib package.
Group: Development
Requires: geocode-glib-lib = %{version}-%{release}
Requires: geocode-glib-data = %{version}-%{release}
Provides: geocode-glib-devel = %{version}-%{release}
Requires: geocode-glib = %{version}-%{release}

%description dev
dev components for the geocode-glib package.


%package doc
Summary: doc components for the geocode-glib package.
Group: Documentation

%description doc
doc components for the geocode-glib package.


%package lib
Summary: lib components for the geocode-glib package.
Group: Libraries
Requires: geocode-glib-data = %{version}-%{release}
Requires: geocode-glib-libexec = %{version}-%{release}
Requires: geocode-glib-license = %{version}-%{release}

%description lib
lib components for the geocode-glib package.


%package libexec
Summary: libexec components for the geocode-glib package.
Group: Default
Requires: geocode-glib-license = %{version}-%{release}

%description libexec
libexec components for the geocode-glib package.


%package license
Summary: license components for the geocode-glib package.
Group: Default

%description license
license components for the geocode-glib package.


%package tests
Summary: tests components for the geocode-glib package.
Group: Default
Requires: geocode-glib = %{version}-%{release}

%description tests
tests components for the geocode-glib package.


%prep
%setup -q -n geocode-glib-3.26.4
cd %{_builddir}/geocode-glib-3.26.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1663961771
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dsoup2=false  builddir
ninja -v -C builddir

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
meson test -C builddir --print-errorlogs || :

%install
mkdir -p %{buildroot}/usr/share/package-licenses/geocode-glib
cp %{_builddir}/geocode-glib-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/geocode-glib/5fb362ef1680e635fe5fb212b55eef4db9ead48f || :
cp %{_builddir}/geocode-glib-%{version}/icons/maki/LICENSE.txt %{buildroot}/usr/share/package-licenses/geocode-glib/b5707bf785ec22684c9374d06eaa874ffbf0d2b8 || :
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GeocodeGlib-2.0.typelib
/usr/share/gir-1.0/*.gir
/usr/share/icons/hicolor/scalable/places/poi-airport.svg
/usr/share/icons/hicolor/scalable/places/poi-bar.svg
/usr/share/icons/hicolor/scalable/places/poi-building.svg
/usr/share/icons/hicolor/scalable/places/poi-bus-stop.svg
/usr/share/icons/hicolor/scalable/places/poi-car.svg
/usr/share/icons/hicolor/scalable/places/poi-light-rail-station.svg
/usr/share/icons/hicolor/scalable/places/poi-marker.svg
/usr/share/icons/hicolor/scalable/places/poi-place-of-worship.svg
/usr/share/icons/hicolor/scalable/places/poi-railway-station.svg
/usr/share/icons/hicolor/scalable/places/poi-restaurant.svg
/usr/share/icons/hicolor/scalable/places/poi-school.svg
/usr/share/icons/hicolor/scalable/places/poi-town.svg

%files dev
%defattr(-,root,root,-)
/usr/include/geocode-glib-2.0/geocode-glib/geocode-backend.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-bounding-box.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-enum-types.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-error.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-forward.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-glib.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-location.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-mock-backend.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-nominatim.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-place.h
/usr/include/geocode-glib-2.0/geocode-glib/geocode-reverse.h
/usr/lib64/libgeocode-glib-2.so
/usr/lib64/pkgconfig/geocode-glib-2.0.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/gtk-doc/html/geocode-glib-2/GeocodeBackend.html
/usr/share/gtk-doc/html/geocode-glib-2/GeocodeBoundingBox.html
/usr/share/gtk-doc/html/geocode-glib-2/GeocodeForward.html
/usr/share/gtk-doc/html/geocode-glib-2/GeocodeLocation.html
/usr/share/gtk-doc/html/geocode-glib-2/GeocodeNominatim.html
/usr/share/gtk-doc/html/geocode-glib-2/GeocodePlace.html
/usr/share/gtk-doc/html/geocode-glib-2/GeocodeReverse.html
/usr/share/gtk-doc/html/geocode-glib-2/annotation-glossary.html
/usr/share/gtk-doc/html/geocode-glib-2/api-index-full.html
/usr/share/gtk-doc/html/geocode-glib-2/ch01.html
/usr/share/gtk-doc/html/geocode-glib-2/geocode-glib-2-geocode-error.html
/usr/share/gtk-doc/html/geocode-glib-2/geocode-glib-2-geocode-mock-backend.html
/usr/share/gtk-doc/html/geocode-glib-2/geocode-glib-2.devhelp2
/usr/share/gtk-doc/html/geocode-glib-2/home.png
/usr/share/gtk-doc/html/geocode-glib-2/index.html
/usr/share/gtk-doc/html/geocode-glib-2/left-insensitive.png
/usr/share/gtk-doc/html/geocode-glib-2/left.png
/usr/share/gtk-doc/html/geocode-glib-2/right-insensitive.png
/usr/share/gtk-doc/html/geocode-glib-2/right.png
/usr/share/gtk-doc/html/geocode-glib-2/style.css
/usr/share/gtk-doc/html/geocode-glib-2/up-insensitive.png
/usr/share/gtk-doc/html/geocode-glib-2/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgeocode-glib-2.so.0
/usr/lib64/libgeocode-glib-2.so.0.0.0

%files libexec
%defattr(-,root,root,-)
/usr/libexec/geocode-glib-2/geo-uri
/usr/libexec/geocode-glib-2/geocode-glib
/usr/libexec/geocode-glib-2/mock-backend

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/geocode-glib/5fb362ef1680e635fe5fb212b55eef4db9ead48f
/usr/share/package-licenses/geocode-glib/b5707bf785ec22684c9374d06eaa874ffbf0d2b8

%files tests
%defattr(-,root,root,-)
/usr/share/installed-tests/geocode-glib-2/geo-uri.test
/usr/share/installed-tests/geocode-glib-2/geocode-glib.test
/usr/share/installed-tests/geocode-glib-2/locale_format.json
/usr/share/installed-tests/geocode-glib-2/locale_name.json
/usr/share/installed-tests/geocode-glib-2/locale_name2.json
/usr/share/installed-tests/geocode-glib-2/mock-backend.test
/usr/share/installed-tests/geocode-glib-2/nominatim-area.json
/usr/share/installed-tests/geocode-glib-2/nominatim-data-type-change.json
/usr/share/installed-tests/geocode-glib-2/nominatim-no-results.json
/usr/share/installed-tests/geocode-glib-2/nominatim-place_rank.json
/usr/share/installed-tests/geocode-glib-2/nominatim-rio.json
/usr/share/installed-tests/geocode-glib-2/osm_type0.json
/usr/share/installed-tests/geocode-glib-2/osm_type1.json
/usr/share/installed-tests/geocode-glib-2/osm_type2.json
/usr/share/installed-tests/geocode-glib-2/pi.json
/usr/share/installed-tests/geocode-glib-2/pub.json
/usr/share/installed-tests/geocode-glib-2/rev.json
/usr/share/installed-tests/geocode-glib-2/rev_fail.json
/usr/share/installed-tests/geocode-glib-2/search.json
/usr/share/installed-tests/geocode-glib-2/search_lat_long.json
/usr/share/installed-tests/geocode-glib-2/xep.json
